In [1]:
import numpy as np

In [2]:
matrix_A = np.array([[2,4,5],[3,5,8],[6,7,8],[1,3,2],[4,5,6]])
print(matrix_A)


[[2 4 5]
 [3 5 8]
 [6 7 8]
 [1 3 2]
 [4 5 6]]


In [3]:
matrix_B = np.array([[4,5],[6,8],[1,3]])
print(matrix_B)

[[4 5]
 [6 8]
 [1 3]]


In [4]:
matrix_C = np.dot(matrix_A,matrix_B)
print(matrix_C)

[[ 37  57]
 [ 50  79]
 [ 74 110]
 [ 24  35]
 [ 52  78]]


In [5]:
New_matrix = np.eye(3)
print(New_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [6]:
matrix_d = np.array([[1,0,0],[0,1,0],[0,0,1]])
print(matrix_d)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


In [7]:
vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [10]:
null_values =np.zeros(10)
print(null_values)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
from numpy import random

In [9]:
random =np.random.rand(3,3,3)
print(random)

[[[0.31823818 0.82120065 0.99256625]
  [0.57867462 0.78355246 0.45045533]
  [0.21596016 0.83408089 0.07848572]]

 [[0.41713806 0.14819699 0.24787322]
  [0.84969285 0.92083748 0.85765815]
  [0.86834159 0.4387792  0.54798298]]

 [[0.15079928 0.65650558 0.26639939]
  [0.29024938 0.55372914 0.1414835 ]
  [0.99651179 0.58663118 0.5389425 ]]]
